sudo: required
services: docker
language: go
go: 1.x
script:
  - DOCKER_CONTENT_TRUST=1 docker build . -t bsycorp/goaws:${TRAVIS_BRANCH}
deploy:
  - provider: script
    script: bash ./scripts/docker-deploy.sh
    on:
      tags: true
      repo: bsycorp/goaws
